version: '3.8'

services:
  voxsa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxsa-rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app-data:/app/data
    restart: on-failure

volumes:
  app-data:
